name: Blogul lui Alex Palcuie la Guvernul României
highlighter: rouge
twitter_username: AlexPalcuie
github_username:  palcu
gems:
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
